name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: sxzz/workflows/.github/workflows/release.yml@5d9fe5c8c741d1c970bfa0eca68a42508c7d90d3 # main
    with:
      publish: true
    permissions:
      contents: write
      id-token: write
